import {RATE} from '../app/research.mjs';
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const routes={commercial:'RTMSDataSvcNrgTrade/getRTMSDataSvcNrgTrade',land:'RTMSDataSvcLandTrade/getRTMSDataSvcLandTrade',industrial:'RTMSDataSvcInduTrade/getRTMSDataSvcInduTrade'};
function decodeXML(s){return String(s).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&').trim();}
const tag=(xml,name)=>decodeXML(xml.match(new RegExp('<'+name+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+name+'>','i'))?.[1]||'');
const num=s=>{const v=Number(String(s).replace(/[ ,]/g,''));return Number.isFinite(v)?v:0;};
export function parseTransactions(xml,type){const code=tag(xml,'resultCode')||tag(xml,'returnReasonCode');if(code&&!/^0+$/.test(code))throw new Error('공공데이터 응답 오류 '+code);if(!/<(?:response|items|item)[\s>]/i.test(xml))throw new Error('공공데이터 응답 형식을 확인할 수 없습니다.');const rows=[...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/gi)].map(([_,x])=>{const date=[tag(x,'dealYear'),tag(x,'dealMonth').padStart(2,'0'),tag(x,'dealDay').padStart(2,'0')].join('-');const name=[tag(x,'sggNm'),tag(x,'umdNm'),tag(x,'jibun')].filter(Boolean).join(' ');const cday=tag(x,'cdealDay');const cancelled=!!cday||['O','Y','해제'].includes(tag(x,'cdealType').toUpperCase());const share=/지분|공유/.test(tag(x,'shareDealingType'));const price=num(tag(x,'dealAmount'));const landArea=num(tag(x,'dealArea')||tag(x,'plottageAr'));const buildingArea=num(tag(x,'buildingAr'));const usage=tag(x,'buildingUse')||tag(x,'jimok');return {id:[type,date,name,price,landArea,buildingArea].join('|'),name,date,price,landArea,buildingArea,usage,landUse:tag(x,'landUse'),buildingType:tag(x,'buildingType'),cancelled,share,source:'국토교통부 실거래 API',verified:false};});return {rows,total:num(tag(xml,'totalCount'))};}
function monthList(month,count){const year=Number(month.slice(0,4)),m=Number(month.slice(4));const list=[];for(let i=0;i<count;i++){const d=new Date(Date.UTC(year,m-1-i,1));list.push(d.getUTCFullYear()+String(d.getUTCMonth()+1).padStart(2,'0'));}return list;}
export async function apiFetch(request,env,fetcher=fetch){const url=new URL(request.url);const path=url.pathname;if(request.method!=='GET')return json({error:'지원하지 않는 요청입니다.'},405);if(path==='/api/status')return json({molit:!!env.MOLIT_API_KEY,ecos:!!env.ECOS_API_KEY,server:true,ocr:false,legalAuto:false,version:'1.0'});if(path==='/api/rate'){if(!env.ECOS_API_KEY)return json({error:'ECOS 인증키가 아직 등록되지 않았습니다. 화면의 기준금리는 '+RATE.date+' 확인 자료입니다.',snapshot:RATE},503);try{const end=new Date();const start=new Date(end);start.setUTCFullYear(start.getUTCFullYear()-1);const fmt=d=>d.toISOString().slice(0,10).replaceAll('-','');const target='https://ecos.bok.or.kr/api/StatisticSearch/'+encodeURIComponent(env.ECOS_API_KEY)+'/json/kr/1/500/722Y001/D/'+fmt(start)+'/'+fmt(end)+'/0101000';const res=await fetcher(target,{signal:AbortSignal.timeout(15000)});if(!res.ok)throw new Error();const data=await res.json();const rows=data.StatisticSearch?.row;if(!Array.isArray(rows)||!rows.length)throw new Error();const row=rows.filter(x=>/^\d{8}$/.test(x.TIME)&&Number.isFinite(Number(x.DATA_VALUE))).sort((a,b)=>b.TIME.localeCompare(a.TIME))[0];if(!row)throw new Error();const value=Number(row.DATA_VALUE);if(value<0||value>30)throw new Error();return json({value,date:row.TIME.slice(0,4)+'-'+row.TIME.slice(4,6)+'-'+row.TIME.slice(6,8),retrieved:new Date().toISOString(),live:true,source:'한국은행 ECOS 722Y001',url:'https://ecos.bok.or.kr'});}catch{return json({error:'ECOS 응답을 확인하지 못했습니다. 기준금리 확인 자료를 유지합니다.',snapshot:RATE},502);}}
if(path==='/api/transactions'){if(!env.MOLIT_API_KEY)return json({error:'국토교통부 실거래 API 인증키가 아직 등록되지 않았습니다. 공공데이터포털에서 해당 3개 서비스를 활용신청한 뒤 서버 MOLIT_API_KEY로 등록하세요. 수동 사례·CSV 입력은 바로 사용할 수 있습니다.'},503);const lawd=url.searchParams.get('lawd')||'',month=url.searchParams.get('month')||'',count=Number(url.searchParams.get('months')||1),type=url.searchParams.get('type');const allowed=['building','retail','land','vacant','farmland','forest','factory','warehouse'];if(!/^\d{5}$/.test(lawd)||!/^20\d{2}(0[1-9]|1[0-2])$/.test(month)||!Number.isInteger(count)||count<1||count>12||!allowed.includes(type))return json({error:'시군구 코드, 조회년월, 물건 유형, 조회기간을 확인하세요.'},400);const now=new Date().toISOString().slice(0,7).replace('-','');if(month>now)return json({error:'미래 계약년월은 조회할 수 없습니다.'},400);const group=['factory','warehouse'].includes(type)?'industrial':['land','vacant','farmland','forest'].includes(type)?'land':'commercial';const warnings=[];let key=String(env.MOLIT_API_KEY);try{key=decodeURIComponent(key);}catch{};let all=[];for(const ym of monthList(month,count)){try{for(let page=1;page<=2;page++){const target=new URL('https://apis.data.go.kr/1613000/'+routes[group]);target.search=new URLSearchParams({serviceKey:key,LAWD_CD:lawd,DEAL_YMD:ym,pageNo:String(page),numOfRows:'1000'}).toString();const response=await fetcher(target,{signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error('제공기관 HTTP 오류');const parsed=parseTransactions(await response.text(),type);all.push(...parsed.rows);if(parsed.total<=page*1000)break;if(page===2)warnings.push(ym+' 조회가 2,000건을 초과해 일부만 표시됩니다.');}}catch{warnings.push(ym+' 응답 확인 실패 · 해당 월 자료 미반영');}}
if(all.length===0&&warnings.length)return json({error:'조회할 실거래 응답을 확보하지 못했습니다. 서비스 활용승인·인증키·제공기관 상태를 확인하세요.',warnings},502);all=all.filter(c=>c.price>0);if(type==='farmland')all=all.filter(c=>['전','답','과수원'].includes(c.usage));if(type==='forest')all=all.filter(c=>c.usage==='임야');if(type==='land'||type==='vacant')all=all.filter(c=>c.usage==='대');const unique=[...new Map(all.map(c=>[c.id,c])).values()].sort((a,b)=>b.date.localeCompare(a.date));if(unique.length>2000)warnings.push('표시 상한 2,000건 초과 · 최근 거래 2,000건만 반환');return json({rows:unique.slice(0,2000),warnings,source:'국토교통부',retrievedAt:new Date().toISOString(),lawd,months:monthList(month,count),scope:'시군구 후보 · 인근 여부와 비교 적합성은 수동 확인'});}
return json({error:'해당 API가 없습니다.'},404);}
