export const RESEARCH_DATE='2026-10-01';
export const RATE={value:3,date:'2026-08-27',retrieved:'2026-10-01',source:'한국은행 통화정책방향',url:'https://www.bok.or.kr/portal/bbs/P0000559/view.do?depth=200690&menuNo=200690&nttId=11064191&oldMenuNo=201150&programType=newsData&relate=Y',live:false};
export const SOURCES=[
{name:'한국은행 · 기준금리',kind:'공식 정책자료',date:'2026.08.27',url:RATE.url,note:'기준금리 3.00% 확인. 개별 금융기관의 부동산 담보대출금리와 다릅니다. ECOS 연결 전에는 확인일 기준 스냅샷입니다.'},
{name:'국토교통부 · 상업업무용 매매 실거래',kind:'공공 API',date:'2026.10.01 확인',url:'https://www.data.go.kr/data/15126463/openapi.do',note:'시군구 코드와 계약년월로 조회. 일반건축물의 지번 일부가 비공개이므로 자동으로 동일 물건이나 인근 거래라고 확정할 수 없습니다.'},
{name:'국토교통부 · 토지 매매 실거래',kind:'공공 API',date:'2026.10.01 확인',url:'https://www.data.go.kr/data/15126466/openapi.do',note:'지목·용도지역·거래면적·금액·해제 여부로 후보를 수집합니다. 공유지분 거래와 해제 거래를 비교평가에서 제외합니다.'},
{name:'국토교통부 · 공장 및 창고 매매 실거래',kind:'공공 API',date:'2026.10.01 확인',url:'https://www.data.go.kr/data/15126470/openapi.do',note:'공장·창고는 별도 거래 자료로 분리. 전력·진입로·하중·층고·소방·산업단지 입주조건을 확인해야 합니다.'},
{name:'국토교통부 · 토지이용규제정보서비스',kind:'추가 연결 대상',date:'2026.10.01 확인',url:'https://www.data.go.kr/data/15058410/openapi.do',note:'지역·지구별 행위제한 정보. 허가 가능 여부는 해당 필지의 규제·조례·접도·인허가 조건을 함께 확인해야 합니다. 현재 앱은 자동 판정하지 않습니다.'},
{name:'국토교통부 · 토지임야정보',kind:'추가 연결 대상',date:'2026.10.01 확인',url:'https://www.data.go.kr/data/15123884/openapi.do',note:'소유자 개인정보를 제외한 소재·지번·지목·면적 확인. 토지대장·임야대장 확인의 기초 자료입니다.'},
{name:'농림축산식품부 · 농지공간포털',kind:'공식 조회서비스',date:'2026.10.01 확인',url:'https://njy.mafra.go.kr/nnjy/main/info/nnjyInfo01.do',note:'농지·농업진흥지역·이용실태·농지취득자격 관련 자료. 도면의 반영 시차와 개인정보 미제공 범위를 확인해야 합니다.'},
{name:'한국부동산원 · 상업용 공실률 정의',kind:'공식 조사 설명',date:'2026.02.11',url:'https://www.reb.or.kr/reb/na/ntt/selectNttInfo.do?mi=9665&nttSn=112048',note:'공실면적 ÷ 임대가능면적. 표본 상권의 공실률과 개별 건물의 실제 공실률은 구분합니다.'},
{name:'CBRE · Seoul Figures Q2 2026',kind:'시장조사 원출처',date:'2026년 2분기',url:'https://www.cbrekorea.com/press-releases/seoul-figures-q2-2026',note:'서울 3대 권역 A급 오피스 공실 4.2%, 수도권 A급 물류 전체 14.6%, 상온 8.7%, 저온 33.0%. 해당 표본 범위의 자료이며 소형 상가·일반 창고에 직접 적용하지 않습니다.'},
{name:'국세청 · 양도소득세 세율',kind:'공식 세무자료',date:'2026.10.01 확인',url:'https://b.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=7711&mi=2312',note:'개인 일반 부동산 기본세율 6~45%, 비사업용 토지 기본세율 +10%p. 단기보유 세율 경합을 비교합니다. 주택·법인·감면 특례는 별도 검토입니다.'},
{name:'국세청 · 장기보유특별공제',kind:'공식 세무자료',date:'2026.10.01 확인',url:'https://i.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=7710&mi=2311',note:'일반 토지·건물은 3년 이상 6%, 연 2%씩 증가하여 15년 이상 30%. 적용 제외 및 특례는 사실관계를 확인해야 합니다.'},
{name:'소득세법 시행령 제168조의6',kind:'현행 법령',date:'시행 2026.07.01',url:'https://www.law.go.kr/LSW/lsLinkCommonInfo.do?chrClsCd=010202&lsJoLnkSeq=1026541899',note:'비사업용 토지 기간기준은 일수로 계산하고 각 보유구간의 요건을 모두 충족하는지 확인합니다. 법정 예외와 실제 사업용 기간의 적격성은 별도로 판단합니다.'},
{name:'생활법령 · 농지취득자격증명',kind:'법제처 설명자료',date:'2026.10.01 확인',url:'https://www.easylaw.go.kr/CSP/CnpClsMain.laf?ccfNo=2&cciNo=3&cnpClsNo=2&csmSeq=93',note:'농취증·경영계획·발급 예외를 검토. 농지 전용과 농업진흥지역 제한은 취득 자격과 별개의 문제입니다.'},
{name:'생활법령 · 농지전용허가',kind:'법제처 설명자료',date:'2026.10.01 확인',url:'https://www.easylaw.go.kr/CSP/CnpClsMain.laf?ccfNo=2&cciNo=1&cnpClsNo=2&csmSeq=1815',note:'전용허가·신고·의제 여부와 허가권자, 부담금 및 목적사업 요건을 확인합니다. 농지에 창고나 주차장을 설치하는 것만으로 사업용 토지가 되는 것은 아닙니다.'},
{name:'서울시 ETAX · 취득세 계산표',kind:'공식 지방세 안내',date:'2026.10.01 확인',url:'https://etax.seoul.go.kr/AcqutaxCalcAction.view?gl_gubun=l&gnb_id=0610&lnb_id=0610',note:'일반 주택 외 유상취득 합계 예시 4.6%, 신규 농지 3.4%. 감면·중과·과표·용도 예외를 확인하고 실제 적용률로 수정합니다.'}
];
export const LEGAL_CHECKS=[{id:'title',title:'등기 · 권리관계',note:'소유자, 근저당, 가압류, 가처분, 지역권·분묘기지권'},{id:'planning',title:'용도지역 · 행위제한',note:'토지이용계획, 조례, 토지거래허가, 개발행위허가'},{id:'access',title:'접도 · 진입로',note:'건축법상 도로, 도로 사용권, 맹지, 대형차 진출입'},{id:'lease',title:'임대차 · 보증금',note:'실제 계약, 체납, 무상임대, 우선변제, 계약승계'},{id:'building',title:'건축물 적법성',note:'건축물대장, 위반건축물, 불법 증축·용도변경',types:['building','retail','factory','warehouse']},{id:'repair',title:'건물 상태 · 수선비',note:'구조·누수·소방·전기, 승강기, 장기 수선계획',types:['building','retail','factory','warehouse']},{id:'farmland',title:'농지 취득 · 이용실태',note:'농취증 대상·예외, 농업진흥지역, 실제 경작, 불법전용',types:['farmland']},{id:'conversion',title:'농지·산지 전용',note:'허가·신고·의제, 부담금·복구비, 제한시설',types:['farmland','forest']},{id:'forest',title:'산지 · 보전산지',note:'보전산지·임업용산지·경사도·산지전용·묘지',types:['forest']},{id:'industry',title:'공장·창고 이용조건',note:'입주 업종, 전력, 층고, 바닥하중, 소방, 환경 인허가',types:['factory','warehouse']},{id:'tax',title:'세무 증빙 · 사업용 이력',note:'취득원가·필요경비·감가상각·일수 이력·법정 예외'},{id:'vat',title:'부가세 · 포괄양수도',note:'토지·건물 안분, 건물분 VAT, 환급 요건, 포괄양수도'}];
